---
name: Lint Code Base

# https://github.com/marketplace/actions/super-linter

# Start the job on all push
on:
  push:
    branches-ignore:
      - "master"

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: docker://github/super-linter:v2.1.0
        env:
          VALIDATE_ALL_CODEBASE: true
